Quarks.gui;

//Quarks from git
Quarks.install("https://github.com/madskjeldgaard/multiencoderdashboard");
Quarks.install("https://github.com/madskjeldgaard/PolyBuf.git");
Quarks.install("https://github.com/madskjeldgaard/KModules.git");
Quarks.install("https://github.com/madskjeldgaard/ndefextensions");
Quarks.install("https://github.com/supercollider-quarks/Bjorklund");
Quarks.install("https://github.com/ModalityTeam/Modality-toolkit.git");
Quarks.install("https://github.com/jamshark70/ddwSnippets.git");
Quarks.install("https://github.com/supercollider-quarks/BatLib");
Quarks.install("https://github.com/supercollider-quarks/LinuxExternal.git");
Quarks.install("https://github.com/supercollider-quarks/Laptop.git");
//senseworld not installing, also webpage not loading http://sensestage.hexagram.ca/
Quarks.install("https://github.com/supercollider-quarks/JoshMisc");
Quarks.install("https://github.com/ambisonictoolkit/atk-sc3.git");
//ATK Installation kernel matrices sounds (rename sounds to sounds)
//-> /home/jason/.local/share/ATK/sounds

//add ATS modular?

//iem vst multiencoder dashboard
Quarks.install("https://github.com/madskjeldgaard/multiencoderdashboard")


// network collab platform
Quarks.install("https://github.com/aiberlin/HyperDisCo")
// visual synth
Quarks.install("https://github.com/ScintillatorSynth/Scintillator")