Quarks.gui;

//Quarks from git
Quarks.install("https://github.com/madskjeldgaard/multiencoderdashboard");
Quarks.install("https://github.com/madskjeldgaard/PolyBuf.git");
Quarks.install("https://github.com/madskjeldgaard/KModules.git");
Quarks.install("https://github.com/madskjeldgaard/ndefextensions");
Quarks.install("https://github.com/supercollider-quarks/Bjorklund");
Quarks.install("https://github.com/ModalityTeam/Modality-toolkit.git");
Quarks.install("https://github.com/jamshark70/ddwSnippets.git");
Quarks.install("https://github.com/supercollider-quarks/BatLib");
Quarks.install("https://github.com/supercollider-quarks/LinuxExternal.git");
Quarks.install("https://github.com/supercollider-quarks/Laptop.git");
//senseworld not installing, also webpage not loading http://sensestage.hexagram.ca/
Quarks.install("https://github.com/supercollider-quarks/autogui");
Quarks.install("https://github.com/supercollider-quarks/JoshMisc");

//add ATS modular?