Quarks.gui;

//Quarks from git
Quarks.install("https://github.com/supercollider-quarks/BatLib");
Quarks.install("https://github.com/cappelnord/BenoitLib");
Quarks.install("https://github.com/supercollider-quarks/Bjorklund");
Quarks.install("https://github.com/ModalityTeam/Modality-toolkit.git");



Quarks.install("https://github.com/madskjeldgaard/multiencoderdashboard");
Quarks.install("https://github.com/madskjeldgaard/PolyBuf.git");
Quarks.install("https://github.com/madskjeldgaard/KModules.git");
Quarks.install("https://github.com/madskjeldgaard/ndefextensions");
//Quarks.install("https://github.com/jamshark70/ddwSnippets.git");
//Quarks.install("https://github.com/supercollider-quarks/LinuxExternal.git");
//Quarks.install("https://github.com/supercollider-quarks/Laptop.git");
//senseworld not installing, also webpage not loading http://sensestage.hexagram.ca/
//Quarks.install("https://github.com/supercollider-quarks/autogui");
Quarks.install("https://github.com/supercollider-quarks/JoshMisc");
Quarks.install("https://github.com/aiberlin/HyperDisCo");


//add ATS modular?

// macOS quarkset july 6 2020
// CCIn
// Ctk
// Dirt Samples
// Ease
// Else
// FileLog
// Hilbert
// HyperDisCo
// JITLibExtensions
// JoshMisc
// KModules
// MathLib
// Particular
// Polybuf
// SuperDiffuse
// SuperDirt
// UGenPatterns
// Vowel
// Wavesets
// XML
// APEX https://github.com/musikinformatik/apex-sc-dafx
// Arduino
// atk-sc3
// ddwSnippets
// miSCellaneous_lib
// say
